---
- name: Crete a file system
  filesystem:
    fstype: "{{ item.fstype }}"
    dev: "{{ item.dev }}"
#TODO: check if force should be set to yes    force: yes
  with_items: "{{ device_names }}"
  ignore_errors: "{{ ansible_check_mode }}"


#- name: Make sure a device is a block one
#  stat:
#    path: "{{ item.dev }}"
#  register: st
#  failed_when: not st.stat.isblk
#  with_items: "{{ device_names}}"

- name: Mount a device
  mount:
    path: "{{ item.path }}"
    src: "{{ item.dev }}"
    fstype: "{{ item.fstype }}"
    state: mounted
  with_items: "{{ device_names}}"
  ignore_errors: "{{ ansible_check_mode }}"
