---
- name: excercise debug 
  hosts: localhost
  connection: local
  
  handlers:
    - name: restart memcached
      debug:
        var: stat.isblk
      listen: "restart web services"

  tasks:
    - name: restart everything
      stat: 
        path: "/dev/xvdp"
      notify: "restart web services"
      changed_when: True

